# Generated by Django 3.2.5 on 2021-07-23 17:46

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='user',
            field=models.CharField(max_length=200, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='schools',
            name='user',
            field=models.CharField(max_length=200, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='table',
            name='user',
            field=models.CharField(max_length=200, verbose_name=django.contrib.auth.models.User),
        ),
    ]
