# Generated by Django 3.2.5 on 2021-07-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_schools_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='classNum',
        ),
        migrations.AlterField(
            model_name='classes',
            name='user',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='table',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
